
/* 
  Dart Background Models and Mock Data for LCD DALULE 
  You can copy and paste this into your Flutter project.
*/

class Brand {
  final String id;
  final String name;
  final String logoUrl;

  Brand({
    required this.id,
    required this.name,
    required this.logoUrl,
  });

  factory Brand.fromJson(Map<String, dynamic> json) {
    return Brand(
      id: json['id'],
      name: json['name'],
      logoUrl: json['logoUrl'],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'logoUrl': logoUrl,
    };
  }
}

class PhoneModel {
  final String id;
  final String brandId;
  final String name;
  final String lcdScreenCode;

  PhoneModel({
    required this.id,
    required this.brandId,
    required this.name,
    required this.lcdScreenCode,
  });

  factory PhoneModel.fromJson(Map<String, dynamic> json) {
    return PhoneModel(
      id: json['id'],
      brandId: json['brandId'],
      name: json['name'],
      lcdScreenCode: json['lcdScreenCode'],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'brandId': brandId,
      'name': name,
      'lcdScreenCode': lcdScreenCode,
    };
  }
}

class CommunitySuggestion {
  final String id;
  final String brand;
  final String model;
  final String suggestedCompatibleCode;
  int likesCount;
  int dislikesCount;
  bool isApproved;

  CommunitySuggestion({
    required this.id,
    required this.brand,
    required this.model,
    required this.suggestedCompatibleCode,
    this.likesCount = 0,
    this.dislikesCount = 0,
    this.isApproved = false,
  });

  // Threshold Rule: likesCount > 50 && likesCount > dislikesCount
  void vote(bool isLike) {
    if (isLike) {
      likesCount++;
    } else {
      dislikesCount++;
    }
    
    if (likesCount > 50 && likesCount > dislikesCount) {
      isApproved = true;
    }
  }
}

// Mock Data List
final List<Brand> mockBrands = [
  Brand(id: 'b1', name: 'Samsung', logoUrl: 'https://logo.clearbit.com/samsung.com'),
  Brand(id: 'b2', name: 'Apple', logoUrl: 'https://logo.clearbit.com/apple.com'),
  Brand(id: 'b3', name: 'Huawei', logoUrl: 'https://logo.clearbit.com/huawei.com'),
  Brand(id: 'b4', name: 'Xiaomi', logoUrl: 'https://logo.clearbit.com/mi.com'),
  Brand(id: 'b5', name: 'Oppo', logoUrl: 'https://logo.clearbit.com/oppo.com'),
  Brand(id: 'b6', name: 'Vivo', logoUrl: 'https://logo.clearbit.com/vivo.com'),
  Brand(id: 'b7', name: 'Realme', logoUrl: 'https://logo.clearbit.com/realme.com'),
  Brand(id: 'b8', name: 'Infinix', logoUrl: 'https://logo.clearbit.com/infinixmobility.com'),
  Brand(id: 'b9', name: 'Tecno', logoUrl: 'https://logo.clearbit.com/tecno-mobile.com'),
  Brand(id: 'b10', name: 'Itel', logoUrl: 'https://logo.clearbit.com/itel-mobile.com'),
  Brand(id: 'b11', name: 'HONOR', logoUrl: 'https://logo.clearbit.com/honor.com'),
];

final List<PhoneModel> mockPhoneModels = [
  PhoneModel(id: 'm1', brandId: 'b1', name: 'Galaxy A10', lcdScreenCode: 'SAM-A10-LCD'),
  PhoneModel(id: 'm2', brandId: 'b1', name: 'Galaxy M10', lcdScreenCode: 'SAM-A10-LCD'),
  PhoneModel(id: 'm3', brandId: 'b2', name: 'iPhone X', lcdScreenCode: 'IPA-X-LCD'),
  PhoneModel(id: 'm4', brandId: 'b2', name: 'iPhone XS', lcdScreenCode: 'IPA-X-LCD'),
  PhoneModel(id: 'm5', brandId: 'b4', name: 'Redmi Note 7', lcdScreenCode: 'XIA-N7-LCD'),
  PhoneModel(id: 'm6', brandId: 'b4', name: 'Redmi Note 7 Pro', lcdScreenCode: 'XIA-N7-LCD'),
  PhoneModel(id: 'm7', brandId: 'b3', name: 'P30 Lite', lcdScreenCode: 'HUW-P30L-LCD'),
  PhoneModel(id: 'm8', brandId: 'b3', name: 'Nova 4e', lcdScreenCode: 'HUW-P30L-LCD'),
  
  // Honor Models
  PhoneModel(id: 'h1', brandId: 'b11', name: 'Honor 10', lcdScreenCode: 'HON-10-LCD'),
  PhoneModel(id: 'h2', brandId: 'b11', name: 'Honor 10i', lcdScreenCode: 'HW-6.21-LCD'),
  PhoneModel(id: 'h3', brandId: 'b11', name: 'Honor 10 Lite', lcdScreenCode: 'HW-6.21-LCD'),
  PhoneModel(id: 'h4', brandId: 'b11', name: 'Honor 20i', lcdScreenCode: 'HW-6.21-LCD'),
  PhoneModel(id: 'h5', brandId: 'b11', name: 'Honor 8A', lcdScreenCode: 'HW-6.09-LCD'),
  PhoneModel(id: 'h6', brandId: 'b11', name: 'Honor 8S', lcdScreenCode: 'HW-5.71-LCD'),
  PhoneModel(id: 'h7', brandId: 'b11', name: 'Honor 8X', lcdScreenCode: 'HON-8X-LCD'),
  PhoneModel(id: 'h8', brandId: 'b11', name: 'Honor 7A 5.45', lcdScreenCode: 'HW-5.45-LCD'),
  PhoneModel(id: 'h9', brandId: 'b11', name: 'Honor 7s', lcdScreenCode: 'HW-5.45-LCD'),
  PhoneModel(id: 'h10', brandId: 'b11', name: 'Honor 9 Lite', lcdScreenCode: 'HUW-P-SMART-LCD'),
  PhoneModel(id: 'h11', brandId: 'b11', name: 'Honor X7a', lcdScreenCode: 'HON-X7A-LCD'),
  PhoneModel(id: 'h12', brandId: 'b11', name: 'Honor X8', lcdScreenCode: 'HON-X8-LCD'),
  PhoneModel(id: 'h13', brandId: 'b11', name: 'Honor 90 Lite', lcdScreenCode: 'HON-90L-LCD'),
  PhoneModel(id: 'h14', brandId: 'b11', name: 'Honor Magic 5 Lite', lcdScreenCode: 'HON-M5L-LCD'),

  // Huawei Models
  PhoneModel(id: 'hw1', brandId: 'b3', name: 'Huawei Enjoy 7s', lcdScreenCode: 'HUW-P-SMART-LCD'),
  PhoneModel(id: 'hw2', brandId: 'b3', name: 'Huawei P Smart (2019)', lcdScreenCode: 'HW-6.21-LCD'),
  PhoneModel(id: 'hw3', brandId: 'b3', name: 'Huawei Y6 (2019)', lcdScreenCode: 'HW-6.09-LCD'),
  PhoneModel(id: 'hw4', brandId: 'b3', name: 'Huawei Y5 (2019)', lcdScreenCode: 'HW-5.71-LCD'),
  PhoneModel(id: 'hw5', brandId: 'b3', name: 'Huawei Y5 (2018)', lcdScreenCode: 'HW-5.45-LCD'),
  PhoneModel(id: 'hw6', brandId: 'b3', name: 'Huawei Y5 Prime (2018)', lcdScreenCode: 'HW-5.45-LCD'),
  PhoneModel(id: 'hw7', brandId: 'b3', name: 'Huawei P Smart Plus', lcdScreenCode: 'HUW-PS-PLUS-LCD'),
  PhoneModel(id: 'hw8', brandId: 'b3', name: 'Huawei Nova Lite (2017)', lcdScreenCode: 'HUW-P8L-LCD'),
  PhoneModel(id: 'hw9', brandId: 'b3', name: 'Huawei P20 Lite', lcdScreenCode: 'HUW-P20L-LCD'),
  PhoneModel(id: 'hw10', brandId: 'b3', name: 'Huawei P40 Lite', lcdScreenCode: 'HUW-P40L-LCD'),
  PhoneModel(id: 'hw11', brandId: 'b3', name: 'Huawei Y70', lcdScreenCode: 'HUW-Y70-LCD'),
  PhoneModel(id: 'hw12', brandId: 'b3', name: 'Huawei Y6 Pro (2019)', lcdScreenCode: 'HW-6.09-LCD'),
  PhoneModel(id: 'hw13', brandId: 'b3', name: 'Huawei Y6p', lcdScreenCode: 'HUW-Y6P-LCD'),
  PhoneModel(id: 'hw14', brandId: 'b3', name: 'Huawei Y6s (2019)', lcdScreenCode: 'HW-6.09-LCD'),
  PhoneModel(id: 'hw15', brandId: 'b3', name: 'Huawei Y7 (2018)', lcdScreenCode: 'HUW-Y7-LCD'),
  PhoneModel(id: 'hw16', brandId: 'b3', name: 'Huawei Y7 (2019)', lcdScreenCode: 'HUW-Y7-LCD'),
  PhoneModel(id: 'hw17', brandId: 'b3', name: 'Huawei Y7 Prime (2018)', lcdScreenCode: 'HUW-Y7-LCD'),
  PhoneModel(id: 'hw18', brandId: 'b3', name: 'Huawei Y7P', lcdScreenCode: 'HUW-Y7P-LCD'),
  PhoneModel(id: 'hw19', brandId: 'b3', name: 'Huawei Y7a', lcdScreenCode: 'HUW-Y7A-LCD'),
  PhoneModel(id: 'hw20', brandId: 'b3', name: 'Huawei Y8p', lcdScreenCode: 'HUW-Y8P-OLED'),
  PhoneModel(id: 'hw21', brandId: 'b3', name: 'Huawei Y9 Prime (2019)', lcdScreenCode: 'HUW-Y9P-LCD'),
  PhoneModel(id: 'hw22', brandId: 'b3', name: 'Huawei Nova 7i', lcdScreenCode: 'HUW-P40L-LCD'),
  PhoneModel(id: 'hw23', brandId: 'b3', name: 'Huawei Nova 8i', lcdScreenCode: 'HUW-N8I-LCD'),
  PhoneModel(id: 'hw24', brandId: 'b3', name: 'Huawei Nova 9 SE', lcdScreenCode: 'HUW-N9SE-LCD'),
  PhoneModel(id: 'hw25', brandId: 'b3', name: 'Huawei Nova Y70', lcdScreenCode: 'HUW-Y70-LCD'),
  PhoneModel(id: 'hw26', brandId: 'b3', name: 'Huawei Nova Y90', lcdScreenCode: 'HUW-Y90-LCD'),
  PhoneModel(id: 'hw27', brandId: 'b3', name: 'Huawei P30 Lite', lcdScreenCode: 'HUW-P30L-LCD'),
  PhoneModel(id: 'hw28', brandId: 'b3', name: 'Huawei P40 Lite', lcdScreenCode: 'HUW-P40L-LCD'),

  // Infinix Models
  PhoneModel(id: 'inf1', brandId: 'b8', name: 'Infinix Smart 5', lcdScreenCode: 'INF-SM5-LCD'),
  PhoneModel(id: 'inf2', brandId: 'b8', name: 'Infinix GT 10 Pro', lcdScreenCode: 'INF-GT10-OLED'),
  PhoneModel(id: 'inf3', brandId: 'b8', name: 'Infinix Hot 10', lcdScreenCode: 'INF-H10-LCD'),
  PhoneModel(id: 'inf4', brandId: 'b8', name: 'Infinix Hot 10 Lite', lcdScreenCode: 'INF-H10-LCD'),
  PhoneModel(id: 'inf5', brandId: 'b8', name: 'Infinix Hot 10i', lcdScreenCode: 'INF-H10I-LCD'),
  PhoneModel(id: 'inf6', brandId: 'b8', name: 'Infinix Hot 11', lcdScreenCode: 'INF-H11-LCD'),
  PhoneModel(id: 'inf7', brandId: 'b8', name: 'Infinix Hot 11s', lcdScreenCode: 'INF-H11S-LCD'),
  PhoneModel(id: 'inf8', brandId: 'b8', name: 'Infinix Hot 12', lcdScreenCode: 'INF-H12-LCD'),
  PhoneModel(id: 'inf9', brandId: 'b8', name: 'Infinix Hot 12 Play', lcdScreenCode: 'INF-H12P-LCD'),
  PhoneModel(id: 'inf10', brandId: 'b8', name: 'Infinix Hot 12i', lcdScreenCode: 'INF-H12I-LCD'),
  PhoneModel(id: 'inf11', brandId: 'b8', name: 'Infinix Hot 20', lcdScreenCode: 'INF-H20-LCD'),
  PhoneModel(id: 'inf12', brandId: 'b8', name: 'Infinix Hot 20 Play', lcdScreenCode: 'INF-H20-LCD'),
  PhoneModel(id: 'inf13', brandId: 'b8', name: 'Infinix Hot 20i', lcdScreenCode: 'INF-H20I-LCD'),
  PhoneModel(id: 'inf14', brandId: 'b8', name: 'Infinix Hot 30', lcdScreenCode: 'INF-H30-LCD'),
  PhoneModel(id: 'inf15', brandId: 'b8', name: 'Infinix Hot 30i', lcdScreenCode: 'INF-H30I-LCD'),
  PhoneModel(id: 'inf16', brandId: 'b8', name: 'Infinix Hot 40', lcdScreenCode: 'INF-H40-LCD'),
  PhoneModel(id: 'inf17', brandId: 'b8', name: 'Infinix Hot 40 Pro', lcdScreenCode: 'INF-H40-LCD'),
  PhoneModel(id: 'inf18', brandId: 'b8', name: 'Infinix Hot 40i', lcdScreenCode: 'INF-H40I-LCD'),
  PhoneModel(id: 'inf19', brandId: 'b8', name: 'Infinix Hot 50i', lcdScreenCode: 'INF-H50I-LCD'),
  PhoneModel(id: 'inf20', brandId: 'b8', name: 'Infinix Note 10 Pro', lcdScreenCode: 'INF-N10P-LCD'),
  PhoneModel(id: 'inf21', brandId: 'b8', name: 'Infinix Note 11', lcdScreenCode: 'INF-N11-AMOLED'),
  PhoneModel(id: 'inf22', brandId: 'b8', name: 'Infinix Note 12', lcdScreenCode: 'INF-N12-AMOLED'),
  PhoneModel(id: 'inf23', brandId: 'b8', name: 'Infinix Note 30', lcdScreenCode: 'INF-N30-LCD'),
  PhoneModel(id: 'inf24', brandId: 'b8', name: 'Infinix Note 30 Pro', lcdScreenCode: 'INF-N30-LCD'),
  PhoneModel(id: 'inf25', brandId: 'b8', name: 'Infinix Note 40', lcdScreenCode: 'INF-N40-AMOLED'),
  PhoneModel(id: 'inf26', brandId: 'b8', name: 'Infinix Note 40 Pro', lcdScreenCode: 'INF-N40-AMOLED'),
  PhoneModel(id: 'inf27', brandId: 'b8', name: 'Infinix Smart 6', lcdScreenCode: 'INF-SM6-LCD'),
  PhoneModel(id: 'inf28', brandId: 'b8', name: 'Infinix Smart 7', lcdScreenCode: 'INF-SM6-LCD'),
  PhoneModel(id: 'inf29', brandId: 'b8', name: 'Infinix Smart 8', lcdScreenCode: 'INF-SM8-LCD'),
  PhoneModel(id: 'inf30', brandId: 'b8', name: 'Infinix Smart 9', lcdScreenCode: 'INF-SM9-LCD'),

  // Oppo Models
  PhoneModel(id: 'op1', brandId: 'b5', name: 'Oppo A12', lcdScreenCode: 'OPP-A12-LCD'),
  PhoneModel(id: 'op2', brandId: 'b5', name: 'Oppo A15', lcdScreenCode: 'OPP-A15-LCD'),
  PhoneModel(id: 'op3', brandId: 'b5', name: 'Oppo A15s', lcdScreenCode: 'OPP-A15-LCD'),
  PhoneModel(id: 'op4', brandId: 'b5', name: 'Oppo A16', lcdScreenCode: 'OPP-A15-LCD'),
  PhoneModel(id: 'op5', brandId: 'b5', name: 'Oppo A17', lcdScreenCode: 'OPP-A17-LCD'),
  PhoneModel(id: 'op6', brandId: 'b5', name: 'Oppo A18', lcdScreenCode: 'OPP-A18-LCD'),
  PhoneModel(id: 'op7', brandId: 'b5', name: 'Oppo A31', lcdScreenCode: 'OPP-A31-LCD'),
  PhoneModel(id: 'op8', brandId: 'b5', name: 'Oppo A38', lcdScreenCode: 'OPP-A38-LCD'),
  PhoneModel(id: 'op9', brandId: 'b5', name: 'Oppo A52', lcdScreenCode: 'OPP-A52-LCD'),
  PhoneModel(id: 'op10', brandId: 'b5', name: 'Oppo A53 4G', lcdScreenCode: 'OPP-A53-LCD'),
  PhoneModel(id: 'op11', brandId: 'b5', name: 'Oppo A54 4G', lcdScreenCode: 'OPP-A54-LCD'),
  PhoneModel(id: 'op12', brandId: 'b5', name: 'Oppo A55 4G', lcdScreenCode: 'OPP-A55-LCD'),
  PhoneModel(id: 'op13', brandId: 'b5', name: 'Oppo A57 4G', lcdScreenCode: 'OPP-A57-LCD'),
  PhoneModel(id: 'op14', brandId: 'b5', name: 'Oppo A58 4G', lcdScreenCode: 'OPP-A58-LCD'),
  PhoneModel(id: 'op15', brandId: 'b5', name: 'Oppo A73 5G', lcdScreenCode: 'OPP-A73-LCD'),
  PhoneModel(id: 'op16', brandId: 'b5', name: 'Oppo Find X2 lite', lcdScreenCode: 'OPP-X2L-OLED'),

  // Mixed Models
  PhoneModel(id: 'nar1', brandId: 'b7', name: 'Narzo 30A', lcdScreenCode: 'OPP-A12-LCD'),
  PhoneModel(id: 'nar2', brandId: 'b7', name: 'Narzo 50A', lcdScreenCode: 'OPP-A12-LCD'),
  
  PhoneModel(id: 'inf31', brandId: 'b8', name: 'Infinix Hot 11s NFC', lcdScreenCode: 'INF-H11S-LCD'),
  PhoneModel(id: 'inf32', brandId: 'b8', name: 'Infinix Hot 12 Play NFC', lcdScreenCode: 'INF-H12P-LCD'),
  PhoneModel(id: 'inf33', brandId: 'b8', name: 'Infinix Hot 30 Play NFC', lcdScreenCode: 'INF-H30-LCD'),
  PhoneModel(id: 'inf34', brandId: 'b8', name: 'Infinix Note 7', lcdScreenCode: 'INF-N7-LCD'),
  PhoneModel(id: 'inf35', brandId: 'b8', name: 'Infinix Note 7 Lite', lcdScreenCode: 'INF-N7-LCD'),
  PhoneModel(id: 'inf36', brandId: 'b8', name: 'Infinix Note 8i', lcdScreenCode: 'INF-N8I-LCD'),
  PhoneModel(id: 'inf37', brandId: 'b8', name: 'Infinix Smart 5 Pro', lcdScreenCode: 'INF-SM5-LCD'),
  PhoneModel(id: 'inf38', brandId: 'b8', name: 'Infinix Smart 7 HD', lcdScreenCode: 'INF-SM6-LCD'),
  PhoneModel(id: 'inf39', brandId: 'b8', name: 'Infinix Smart 8 Plus', lcdScreenCode: 'INF-SM8-LCD'),
  PhoneModel(id: 'inf40', brandId: 'b8', name: 'Infinix Zero 30 4G', lcdScreenCode: 'INF-Z30-OLED'),
  PhoneModel(id: 'inf41', brandId: 'b8', name: 'Infinix Zero 30 5G', lcdScreenCode: 'INF-Z30-OLED'),
  PhoneModel(id: 'inf42', brandId: 'b8', name: 'Infinix Zero 40 4G', lcdScreenCode: 'INF-Z40-OLED'),
  PhoneModel(id: 'inf43', brandId: 'b8', name: 'Infinix Zero 40 5G', lcdScreenCode: 'INF-Z40-OLED'),
  PhoneModel(id: 'inf44', brandId: 'b8', name: 'Infinix Zero 8', lcdScreenCode: 'INF-Z8-LCD'),
  PhoneModel(id: 'inf45', brandId: 'b8', name: 'Infinix Zero 8i', lcdScreenCode: 'INF-Z8-LCD'),
  PhoneModel(id: 'inf46', brandId: 'b8', name: 'Infinix Zero X', lcdScreenCode: 'INF-ZX-AMOLED'),
  PhoneModel(id: 'inf47', brandId: 'b8', name: 'Infinix Zero X Neo', lcdScreenCode: 'INF-ZX-AMOLED'),
  PhoneModel(id: 'inf48', brandId: 'b8', name: 'Infinix Zero X Pro', lcdScreenCode: 'INF-ZX-AMOLED'),

  // Oppo additional
  PhoneModel(id: 'op17', brandId: 'b5', name: 'Oppo A1 5G', lcdScreenCode: 'OPP-A1-LCD'),
  PhoneModel(id: 'op18', brandId: 'b5', name: 'Oppo A16s', lcdScreenCode: 'OPP-A15-LCD'),
  PhoneModel(id: 'op19', brandId: 'b5', name: 'Oppo A17k', lcdScreenCode: 'OPP-A17-LCD'),
  PhoneModel(id: 'op21', brandId: 'b5', name: 'Oppo A1K', lcdScreenCode: 'OPP-A1K-LCD'),
  PhoneModel(id: 'op22', brandId: 'b5', name: 'Oppo A3', lcdScreenCode: 'OPP-A3-LCD'),
  PhoneModel(id: 'op23', brandId: 'b5', name: 'Oppo A32', lcdScreenCode: 'OPP-A53-LCD'),
  PhoneModel(id: 'op24', brandId: 'b5', name: 'Oppo A33 (2020)', lcdScreenCode: 'OPP-A53-LCD'),
  PhoneModel(id: 'op25', brandId: 'b5', name: 'Oppo A35', lcdScreenCode: 'OPP-A15-LCD'),
  PhoneModel(id: 'op26', brandId: 'b5', name: 'Oppo A36', lcdScreenCode: 'OPP-A36-LCD'),
  PhoneModel(id: 'op27', brandId: 'b5', name: 'Oppo A53 5G', lcdScreenCode: 'OPP-A53-LCD'),
  PhoneModel(id: 'op28', brandId: 'b5', name: 'Oppo A53s 4G', lcdScreenCode: 'OPP-A53-LCD'),
  PhoneModel(id: 'op29', brandId: 'b5', name: 'Oppo A54 5G', lcdScreenCode: 'OPP-A54-LCD'),
  PhoneModel(id: 'op30', brandId: 'b5', name: 'Oppo A54s', lcdScreenCode: 'OPP-A54-LCD'),
  PhoneModel(id: 'op31', brandId: 'b5', name: 'Oppo A55 5G', lcdScreenCode: 'OPP-A55-LCD'),
  PhoneModel(id: 'op32', brandId: 'b5', name: 'Oppo A56 5G', lcdScreenCode: 'OPP-A56-LCD'),
  PhoneModel(id: 'op33', brandId: 'b5', name: 'Oppo A57 5G', lcdScreenCode: 'OPP-A57-LCD'),
  PhoneModel(id: 'op34', brandId: 'b5', name: 'Oppo A57S', lcdScreenCode: 'OPP-A57-LCD'),
  PhoneModel(id: 'op35', brandId: 'b5', name: 'Oppo A57e', lcdScreenCode: 'OPP-A57-LCD'),

  // Oppo additional 2
  PhoneModel(id: 'op36', brandId: 'b5', name: 'Oppo A58 5G', lcdScreenCode: 'OPP-A58-LCD'),
  PhoneModel(id: 'op37', brandId: 'b5', name: 'Oppo A59 5G', lcdScreenCode: 'OPP-A58-LCD'),
  PhoneModel(id: 'op38', brandId: 'b5', name: 'Oppo A60', lcdScreenCode: 'OPP-A60-LCD'),
  PhoneModel(id: 'op39', brandId: 'b5', name: 'Oppo A7', lcdScreenCode: 'OPP-A7-LCD'),
  PhoneModel(id: 'op40', brandId: 'b5', name: 'Oppo A71', lcdScreenCode: 'OPP-A71-LCD'),
  PhoneModel(id: 'op41', brandId: 'b5', name: 'Oppo A72', lcdScreenCode: 'OPP-A52-LCD'),
  PhoneModel(id: 'op42', brandId: 'b5', name: 'Oppo A73 4G', lcdScreenCode: 'OPP-A73-OLED'),
  PhoneModel(id: 'op43', brandId: 'b5', name: 'Oppo A74 4G', lcdScreenCode: 'OPP-A74-OLED'),
  PhoneModel(id: 'op44', brandId: 'b5', name: 'Oppo A74 5G', lcdScreenCode: 'OPP-A74-LCD'),
  PhoneModel(id: 'op45', brandId: 'b5', name: 'Oppo A76', lcdScreenCode: 'OPP-A76-LCD'),
  PhoneModel(id: 'op46', brandId: 'b5', name: 'Oppo A77 4G', lcdScreenCode: 'OPP-A77-LCD'),
  PhoneModel(id: 'op47', brandId: 'b5', name: 'Oppo A77 5G', lcdScreenCode: 'OPP-A77-LCD'),
  PhoneModel(id: 'op48', brandId: 'b5', name: 'Oppo A77s', lcdScreenCode: 'OPP-A77-LCD'),
  PhoneModel(id: 'op49', brandId: 'b5', name: 'Oppo A78 4G', lcdScreenCode: 'OPP-A78-OLED'),
  PhoneModel(id: 'op50', brandId: 'b5', name: 'Oppo A78 5G', lcdScreenCode: 'OPP-A78-LCD'),
  PhoneModel(id: 'op51', brandId: 'b5', name: 'Oppo A79 5G', lcdScreenCode: 'OPP-A79-LCD'),
  PhoneModel(id: 'op52', brandId: 'b5', name: 'Oppo A8', lcdScreenCode: 'OPP-A31-LCD'),
  PhoneModel(id: 'op53', brandId: 'b5', name: 'Oppo A83', lcdScreenCode: 'OPP-A83-LCD'),
  PhoneModel(id: 'op54', brandId: 'b5', name: 'Oppo A91', lcdScreenCode: 'OPP-A91-OLED'),
  PhoneModel(id: 'op55', brandId: 'b5', name: 'Oppo A92', lcdScreenCode: 'OPP-A52-LCD'),
  PhoneModel(id: 'op56', brandId: 'b5', name: 'Oppo A93 4G', lcdScreenCode: 'OPP-A93-OLED'),
  PhoneModel(id: 'op57', brandId: 'b5', name: 'Oppo A94 4G', lcdScreenCode: 'OPP-A94-OLED'),
  PhoneModel(id: 'op58', brandId: 'b5', name: 'Oppo A95 4G', lcdScreenCode: 'OPP-A74-OLED'),
  PhoneModel(id: 'op59', brandId: 'b5', name: 'Oppo A96 4G', lcdScreenCode: 'OPP-A96-LCD'),
  PhoneModel(id: 'op60', brandId: 'b5', name: 'Oppo A98 5G', lcdScreenCode: 'OPP-A98-LCD'),
  PhoneModel(id: 'op61', brandId: 'b5', name: 'Oppo F11', lcdScreenCode: 'OPP-F11-LCD'),
  PhoneModel(id: 'op62', brandId: 'b5', name: 'Oppo F11 Pro', lcdScreenCode: 'OPP-F11P-LCD'),
  PhoneModel(id: 'op63', brandId: 'b5', name: 'Oppo F15', lcdScreenCode: 'OPP-A91-OLED'),
  PhoneModel(id: 'op64', brandId: 'b5', name: 'Oppo F17', lcdScreenCode: 'OPP-A73-OLED'),
  PhoneModel(id: 'op65', brandId: 'b5', name: 'Oppo F17 Pro', lcdScreenCode: 'OPP-A93-OLED'),
  PhoneModel(id: 'op66', brandId: 'b5', name: 'Oppo F19', lcdScreenCode: 'OPP-A74-OLED'),
  PhoneModel(id: 'op67', brandId: 'b5', name: 'Oppo F19 Pro', lcdScreenCode: 'OPP-A94-OLED'),
  PhoneModel(id: 'op68', brandId: 'b5', name: 'Oppo F19 Pro Plus', lcdScreenCode: 'OPP-A94-OLED'),
  PhoneModel(id: 'op69', brandId: 'b5', name: 'Oppo F19s', lcdScreenCode: 'OPP-A74-OLED'),
  PhoneModel(id: 'op70', brandId: 'b5', name: 'Oppo F1s', lcdScreenCode: 'OPP-F1S-LCD'),
  PhoneModel(id: 'op71', brandId: 'b5', name: 'Oppo F3', lcdScreenCode: 'OPP-F3-LCD'),
  PhoneModel(id: 'op72', brandId: 'b5', name: 'Oppo F5', lcdScreenCode: 'OPP-F5-LCD'),
  PhoneModel(id: 'op73', brandId: 'b5', name: 'Oppo F7', lcdScreenCode: 'OPP-F7-LCD'),
  PhoneModel(id: 'op74', brandId: 'b5', name: 'Oppo F9 / F9 Pro', lcdScreenCode: 'OPP-F9-LCD'),
  PhoneModel(id: 'op75', brandId: 'b5', name: 'Oppo Find X2', lcdScreenCode: 'OPP-X2-OLED'),
  PhoneModel(id: 'op76', brandId: 'b5', name: 'Oppo Find X2 Pro', lcdScreenCode: 'OPP-X2P-OLED'),
  PhoneModel(id: 'op77', brandId: 'b5', name: 'Oppo Find X3 Lite', lcdScreenCode: 'OPP-X3L-OLED'),
  PhoneModel(id: 'op78', brandId: 'b5', name: 'Oppo Find X3 Neo', lcdScreenCode: 'OPP-X3N-OLED'),
  PhoneModel(id: 'op79', brandId: 'b5', name: 'Oppo Find X3 Pro', lcdScreenCode: 'OPP-X3P-OLED'),
  PhoneModel(id: 'op80', brandId: 'b5', name: 'Oppo Find X5', lcdScreenCode: 'OPP-X5-OLED'),
  PhoneModel(id: 'op81', brandId: 'b5', name: 'Oppo Find X5 Lite', lcdScreenCode: 'OPP-X5L-OLED'),
  PhoneModel(id: 'op82', brandId: 'b5', name: 'Oppo Find X5 Pro', lcdScreenCode: 'OPP-X5P-OLED'),

  // Realme Models
  PhoneModel(id: 'rl1', brandId: 'b7', name: 'Realme 10 4G', lcdScreenCode: 'RLM-10-AMOLED'),
  PhoneModel(id: 'rl2', brandId: 'b7', name: 'Realme 10 5G', lcdScreenCode: 'RLM-10-LCD'),
  PhoneModel(id: 'rl3', brandId: 'b7', name: 'Realme 10 Pro', lcdScreenCode: 'RLM-10P-LCD'),
  PhoneModel(id: 'rl4', brandId: 'b7', name: 'Realme 10 Pro Plus', lcdScreenCode: 'RLM-10PP-OLED'),
  PhoneModel(id: 'rl5', brandId: 'b7', name: 'Realme 11 4G', lcdScreenCode: 'RLM-11-AMOLED'),
  PhoneModel(id: 'rl6', brandId: 'b7', name: 'Realme 11 5G', lcdScreenCode: 'RLM-11-LCD'),
  PhoneModel(id: 'rl7', brandId: 'b7', name: 'Realme 11 Pro', lcdScreenCode: 'RLM-11P-OLED'),
  PhoneModel(id: 'rl8', brandId: 'b7', name: 'Realme 11 Pro Plus', lcdScreenCode: 'RLM-11P-OLED'),
  PhoneModel(id: 'rl9', brandId: 'b7', name: 'Realme 11x 5G', lcdScreenCode: 'RLM-11-LCD'),
  PhoneModel(id: 'rl10', brandId: 'b7', name: 'Realme 12 5G', lcdScreenCode: 'RLM-12-LCD'),
  PhoneModel(id: 'rl11', brandId: 'b7', name: 'Realme 12 Pro', lcdScreenCode: 'RLM-12P-OLED'),
  PhoneModel(id: 'rl12', brandId: 'b7', name: 'Realme 12 Pro Plus', lcdScreenCode: 'RLM-12P-OLED'),
  PhoneModel(id: 'rl13', brandId: 'b7', name: 'Realme 12+ 5G', lcdScreenCode: 'RLM-12-AMOLED'),
  PhoneModel(id: 'rl14', brandId: 'b7', name: 'Realme 12x', lcdScreenCode: 'RLM-12X-LCD'),

  // Samsung Models
  PhoneModel(id: 'sa1', brandId: 'b1', name: 'Samsung A01 (A015F)', lcdScreenCode: 'SAM-A01-LCD'),
  PhoneModel(id: 'sa2', brandId: 'b1', name: 'Samsung A01 Core', lcdScreenCode: 'SAM-A01C-LCD'),
  PhoneModel(id: 'sa3', brandId: 'b1', name: 'Samsung A02 (A022F)', lcdScreenCode: 'SAM-A02-LCD'),
  PhoneModel(id: 'sa4', brandId: 'b1', name: 'Samsung A02s (A025F)', lcdScreenCode: 'SAM-A02S-LCD'),
  PhoneModel(id: 'sa5', brandId: 'b1', name: 'Samsung A03 (A035F)', lcdScreenCode: 'SAM-A03-LCD'),
  PhoneModel(id: 'sa6', brandId: 'b1', name: 'Samsung A03 Core (A032F)', lcdScreenCode: 'SAM-A03C-LCD'),
  PhoneModel(id: 'sa7', brandId: 'b1', name: 'Samsung A03s (A037F)', lcdScreenCode: 'SAM-A02S-LCD'),
  PhoneModel(id: 'sa8', brandId: 'b1', name: 'Samsung A04 (A045F)', lcdScreenCode: 'SAM-A04-LCD'),
  PhoneModel(id: 'sa9', brandId: 'b1', name: 'Samsung A04e (A042F)', lcdScreenCode: 'SAM-A04-LCD'),
  PhoneModel(id: 'sa10', brandId: 'b1', name: 'Samsung A04s (A047F)', lcdScreenCode: 'SAM-A12-LCD'),
  PhoneModel(id: 'sa11', brandId: 'b1', name: 'Samsung A05 (A055F)', lcdScreenCode: 'SAM-A05-LCD'),
  PhoneModel(id: 'sa12', brandId: 'b1', name: 'Samsung A05s (A057F)', lcdScreenCode: 'SAM-A05S-LCD'),
  PhoneModel(id: 'sa13', brandId: 'b1', name: 'Samsung A10 (A105F)', lcdScreenCode: 'SAM-A10-LCD'),
  PhoneModel(id: 'sa14', brandId: 'b1', name: 'Samsung A10s (A107F)', lcdScreenCode: 'SAM-A10S-LCD'),
  PhoneModel(id: 'sa15', brandId: 'b1', name: 'Samsung A11 (A115F)', lcdScreenCode: 'SAM-A11-LCD'),
  PhoneModel(id: 'sa16', brandId: 'b1', name: 'Samsung A12 (A125F)', lcdScreenCode: 'SAM-A12-LCD'),
  PhoneModel(id: 'sa17', brandId: 'b1', name: 'Samsung A12 Nacho (A127F)', lcdScreenCode: 'SAM-A12-LCD'),
  PhoneModel(id: 'sa18', brandId: 'b1', name: 'Samsung A13 4G (A135F)', lcdScreenCode: 'SAM-A13-LCD'),
  PhoneModel(id: 'sa19', brandId: 'b1', name: 'Samsung A13 5G (A136B)', lcdScreenCode: 'SAM-A13C-LCD'),
  PhoneModel(id: 'sa20', brandId: 'b1', name: 'Samsung A14 4G (A145F)', lcdScreenCode: 'SAM-A14-LCD'),
  PhoneModel(id: 'sa21', brandId: 'b1', name: 'Samsung A14 5G (A146B)', lcdScreenCode: 'SAM-A14-LCD'),
  PhoneModel(id: 'sa22', brandId: 'b1', name: 'Samsung A15 4G/5G', lcdScreenCode: 'SAM-A15-AMOLED'),
  PhoneModel(id: 'sa23', brandId: 'b1', name: 'Samsung A20 (A205F)', lcdScreenCode: 'SAM-A20-AMOLED'),
  PhoneModel(id: 'sa24', brandId: 'b1', name: 'Samsung A20e', lcdScreenCode: 'SAM-A20E-LCD'),
  PhoneModel(id: 'sa25', brandId: 'b1', name: 'Samsung A20s (A207F)', lcdScreenCode: 'SAM-A20S-LCD'),
  PhoneModel(id: 'sa26', brandId: 'b1', name: 'Samsung A21s (A217F)', lcdScreenCode: 'SAM-A21S-LCD'),
  PhoneModel(id: 'sa27', brandId: 'b1', name: 'Samsung A22 4G (A225F)', lcdScreenCode: 'SAM-A22-AMOLED'),
  PhoneModel(id: 'sa28', brandId: 'b1', name: 'Samsung A22 5G (A226B)', lcdScreenCode: 'SAM-A22-LCD'),
  PhoneModel(id: 'sa29', brandId: 'b1', name: 'Samsung A23 4G (A235F)', lcdScreenCode: 'SAM-A23-LCD'),
  PhoneModel(id: 'sa30', brandId: 'b1', name: 'Samsung A23 5G (A236B)', lcdScreenCode: 'SAM-A23-LCD'),
  PhoneModel(id: 'sa31', brandId: 'b1', name: 'Samsung A24 4G (A245F)', lcdScreenCode: 'SAM-A24-AMOLED'),
  PhoneModel(id: 'sa32', brandId: 'b1', name: 'Samsung A25 5G (A256B)', lcdScreenCode: 'SAM-A25-AMOLED'),
  PhoneModel(id: 'sa33', brandId: 'b1', name: 'Samsung A30 (A305F)', lcdScreenCode: 'SAM-A30-AMOLED'),
  PhoneModel(id: 'sa34', brandId: 'b1', name: 'Samsung A30s (A307F)', lcdScreenCode: 'SAM-A30-AMOLED'),
  PhoneModel(id: 'sa35', brandId: 'b1', name: 'Samsung A31 (A315F)', lcdScreenCode: 'SAM-A31-AMOLED'),
  PhoneModel(id: 'sa36', brandId: 'b1', name: 'Samsung A32 4G (A325F)', lcdScreenCode: 'SAM-A32-AMOLED'),
  PhoneModel(id: 'sa37', brandId: 'b1', name: 'Samsung A32 5G (A326B)', lcdScreenCode: 'SAM-A32-LCD'),
  PhoneModel(id: 'sa38', brandId: 'b1', name: 'Samsung A33 5G (A336B)', lcdScreenCode: 'SAM-A33-AMOLED'),
  PhoneModel(id: 'sa39', brandId: 'b1', name: 'Samsung A34 5G (A346B)', lcdScreenCode: 'SAM-A34-AMOLED'),
  PhoneModel(id: 'sa40', brandId: 'b1', name: 'Samsung A35 5G (A356B)', lcdScreenCode: 'SAM-A35-AMOLED'),
  PhoneModel(id: 'sa41', brandId: 'b1', name: 'Samsung A50 (A505F)', lcdScreenCode: 'SAM-A50-AMOLED'),
  PhoneModel(id: 'sa42', brandId: 'b1', name: 'Samsung A51 4G (A515F)', lcdScreenCode: 'SAM-A51-AMOLED'),
  PhoneModel(id: 'sa43', brandId: 'b1', name: 'Samsung A51 5G (A516B)', lcdScreenCode: 'SAM-A51-AMOLED'),
  PhoneModel(id: 'sa44', brandId: 'b1', name: 'Samsung A52 4G/5G', lcdScreenCode: 'SAM-A52-AMOLED'),
  PhoneModel(id: 'sa45', brandId: 'b1', name: 'Samsung A52s 5G (A528B)', lcdScreenCode: 'SAM-A52-AMOLED'),
  PhoneModel(id: 'sa46', brandId: 'b1', name: 'Samsung A53 5G (A536B)', lcdScreenCode: 'SAM-A53-AMOLED'),
  PhoneModel(id: 'sa47', brandId: 'b1', name: 'Samsung A54 5G (A546B)', lcdScreenCode: 'SAM-A54-AMOLED'),
  PhoneModel(id: 'sa48', brandId: 'b1', name: 'Samsung A55 5G (A556B)', lcdScreenCode: 'SAM-A55-AMOLED'),
  PhoneModel(id: 'sa49', brandId: 'b1', name: 'Samsung A70 (A705F)', lcdScreenCode: 'SAM-A70-AMOLED'),
  PhoneModel(id: 'sa50', brandId: 'b1', name: 'Samsung A71 4G (A715F)', lcdScreenCode: 'SAM-A71-AMOLED'),
  PhoneModel(id: 'sa51', brandId: 'b1', name: 'Samsung A72 4G/5G (A725F)', lcdScreenCode: 'SAM-A72-AMOLED'),
  PhoneModel(id: 'sa52', brandId: 'b1', name: 'Samsung A73 5G (A736B)', lcdScreenCode: 'SAM-A73-AMOLED'),
  PhoneModel(id: 'sa53', brandId: 'b1', name: 'Samsung M10 (M105F)', lcdScreenCode: 'SAM-A10-LCD'),
  PhoneModel(id: 'sa54', brandId: 'b1', name: 'Samsung M11 (M115F)', lcdScreenCode: 'SAM-A11-LCD'),
  PhoneModel(id: 'sa55', brandId: 'b1', name: 'Samsung M12 (M127F)', lcdScreenCode: 'SAM-A12-LCD'),
  PhoneModel(id: 'sa56', brandId: 'b1', name: 'Samsung M20 (M205F)', lcdScreenCode: 'SAM-M20-LCD'),
  PhoneModel(id: 'sa57', brandId: 'b1', name: 'Samsung M21 (M215F)', lcdScreenCode: 'SAM-M21-AMOLED'),
  PhoneModel(id: 'sa58', brandId: 'b1', name: 'Samsung M30 (M305F)', lcdScreenCode: 'SAM-M30-AMOLED'),
  PhoneModel(id: 'sa59', brandId: 'b1', name: 'Samsung M30s (M307F)', lcdScreenCode: 'SAM-M30-AMOLED'),
  PhoneModel(id: 'sa60', brandId: 'b1', name: 'Samsung M31 (M315F)', lcdScreenCode: 'SAM-M31-AMOLED'),
  PhoneModel(id: 'sa61', brandId: 'b1', name: 'Samsung M31s (M317F)', lcdScreenCode: 'SAM-M31S-AMOLED'),
  PhoneModel(id: 'sa62', brandId: 'b1', name: 'Samsung M51 (M515F)', lcdScreenCode: 'SAM-M51-AMOLED'),

  // Tecno Models
  PhoneModel(id: 'tc1', brandId: 'b9', name: 'Tecno Camon 11 (CF7)', lcdScreenCode: 'TEC-C11-LCD'),
  PhoneModel(id: 'tc2', brandId: 'b9', name: 'Tecno Camon 11 Pro (CF8)', lcdScreenCode: 'TEC-C11-LCD'),
  PhoneModel(id: 'tc3', brandId: 'b9', name: 'Tecno Camon 12 (CC7)', lcdScreenCode: 'TEC-C12-LCD'),
  PhoneModel(id: 'tc4', brandId: 'b9', name: 'Tecno Camon 12 Air (CC6)', lcdScreenCode: 'TEC-C12A-LCD'),
  PhoneModel(id: 'tc5', brandId: 'b9', name: 'Tecno Camon 12 Pro (CC9)', lcdScreenCode: 'TEC-C12-AMOLED'),
  PhoneModel(id: 'tc6', brandId: 'b9', name: 'Tecno Camon 15 (CD7)', lcdScreenCode: 'TEC-C15-LCD'),
  PhoneModel(id: 'tc7', brandId: 'b9', name: 'Tecno Camon 15 Air (CD6)', lcdScreenCode: 'TEC-C15-LCD'),
  PhoneModel(id: 'tc8', brandId: 'b9', name: 'Tecno Camon 15 Pro (CD8)', lcdScreenCode: 'TEC-C15P-LCD'),
  PhoneModel(id: 'tc9', brandId: 'b9', name: 'Tecno Camon 16 (CE7)', lcdScreenCode: 'TEC-C16-LCD'),
  PhoneModel(id: 'tc10', brandId: 'b9', name: 'Tecno Camon 16 Premier (CE9)', lcdScreenCode: 'TEC-C16P-LCD'),
  PhoneModel(id: 'tc11', brandId: 'b9', name: 'Tecno Camon 16 Pro (CE8)', lcdScreenCode: 'TEC-C16-LCD'),
  PhoneModel(id: 'tc12', brandId: 'b9', name: 'Tecno Camon 17 (CG6)', lcdScreenCode: 'TEC-C17-LCD'),
  PhoneModel(id: 'tc13', brandId: 'b9', name: 'Tecno Camon 17 Pro (CG8)', lcdScreenCode: 'TEC-C17-LCD'),
  PhoneModel(id: 'tc14', brandId: 'b9', name: 'Tecno Camon 17P (CG7)', lcdScreenCode: 'TEC-C17-LCD'),
  PhoneModel(id: 'tc15', brandId: 'b9', name: 'Tecno Camon 18 (CH6)', lcdScreenCode: 'TEC-C18-LCD'),
  PhoneModel(id: 'tc16', brandId: 'b9', name: 'Tecno Camon 18 Premier (CH9)', lcdScreenCode: 'TEC-C18-AMOLED'),
  PhoneModel(id: 'tc17', brandId: 'b9', name: 'Tecno Camon 18i (CH6I)', lcdScreenCode: 'TEC-C18-LCD'),
  PhoneModel(id: 'tc18', brandId: 'b9', name: 'Tecno Camon 18P (CH7)', lcdScreenCode: 'TEC-C18-LCD'),
  PhoneModel(id: 'tc19', brandId: 'b9', name: 'Tecno Camon 19 (CI6)', lcdScreenCode: 'TEC-C19-LCD'),
  PhoneModel(id: 'tc20', brandId: 'b9', name: 'Tecno Camon 19 Neo (CI6N)', lcdScreenCode: 'TEC-C19-LCD'),
  PhoneModel(id: 'tc21', brandId: 'b9', name: 'Tecno Camon 19 Pro (CI8)', lcdScreenCode: 'TEC-C19-LCD'),
  PhoneModel(id: 'tc22', brandId: 'b9', name: 'Tecno Camon 19 Pro 5G (CI7n)', lcdScreenCode: 'TEC-C19-LCD'),
  PhoneModel(id: 'tc23', brandId: 'b9', name: 'Tecno Camon 20 (CH6i)', lcdScreenCode: 'TEC-C20-AMOLED'),
  PhoneModel(id: 'tc24', brandId: 'b9', name: 'Tecno Camon 20 Pro (CK6n)', lcdScreenCode: 'TEC-C20-AMOLED'),
  PhoneModel(id: 'tc25', brandId: 'b9', name: 'Tecno Camon 20 Pro 5G (CK8n)', lcdScreenCode: 'TEC-C20-AMOLED'),
  PhoneModel(id: 'tc26', brandId: 'b9', name: 'Tecno Camon 20 Premier 5G (CK9n)', lcdScreenCode: 'TEC-C20-AMOLED'),
  PhoneModel(id: 'tc27', brandId: 'b9', name: 'Tecno Pop 5 (BD2)', lcdScreenCode: 'TEC-BD2-LCD'),
  PhoneModel(id: 'tc28', brandId: 'b9', name: 'Tecno Pop 5 Go (BD1)', lcdScreenCode: 'TEC-BD2-LCD'),
  PhoneModel(id: 'tc29', brandId: 'b9', name: 'Tecno Pop 5 LTE (BD6)', lcdScreenCode: 'TEC-BD6-LCD'),
  PhoneModel(id: 'tc30', brandId: 'b9', name: 'Tecno Pop 5 Pro (BD4)', lcdScreenCode: 'TEC-BD6-LCD'),
  PhoneModel(id: 'tc31', brandId: 'b9', name: 'Tecno Pop 6 (BE6)', lcdScreenCode: 'TEC-BE6-LCD'),
  PhoneModel(id: 'tc32', brandId: 'b9', name: 'Tecno Pop 6 Pro (BE8)', lcdScreenCode: 'TEC-BE8-LCD'),
  PhoneModel(id: 'tc33', brandId: 'b9', name: 'Tecno Pop 7 (BF6)', lcdScreenCode: 'TEC-BF6-LCD'),
  PhoneModel(id: 'tc34', brandId: 'b9', name: 'Tecno Pop 7 Pro (BF7)', lcdScreenCode: 'TEC-BF7-LCD'),
  PhoneModel(id: 'tc35', brandId: 'b9', name: 'Tecno Pova 2 (LE7)', lcdScreenCode: 'TEC-LE7-LCD'),
  PhoneModel(id: 'tc36', brandId: 'b9', name: 'Tecno Pova 3 (LF7)', lcdScreenCode: 'TEC-LF7-LCD'),
  PhoneModel(id: 'tc37', brandId: 'b9', name: 'Tecno Pova 4 (LG7)', lcdScreenCode: 'TEC-LG7-LCD'),
  PhoneModel(id: 'tc38', brandId: 'b9', name: 'Tecno Pova 4 Pro (LG8)', lcdScreenCode: 'TEC-LG8-AMOLED'),
  PhoneModel(id: 'tc39', brandId: 'b9', name: 'Tecno Pova 5 (LH7n)', lcdScreenCode: 'TEC-LH7-LCD'),
  PhoneModel(id: 'tc40', brandId: 'b9', name: 'Tecno Pova 5 Pro 5G (LH8n)', lcdScreenCode: 'TEC-LH8-LCD'),
  PhoneModel(id: 'tc41', brandId: 'b9', name: 'Tecno Pova Neo (LE6)', lcdScreenCode: 'TEC-LE6-LCD'),
  PhoneModel(id: 'tc42', brandId: 'b9', name: 'Tecno Pova Neo 2 (LG6n)', lcdScreenCode: 'TEC-LG6-LCD'),
  PhoneModel(id: 'tc43', brandId: 'b9', name: 'Tecno Pova Neo 3 (LH6n)', lcdScreenCode: 'TEC-LH6-LCD'),
  PhoneModel(id: 'tc44', brandId: 'b9', name: 'Tecno Spark 10 (KI5k)', lcdScreenCode: 'TEC-KI5-LCD'),
  PhoneModel(id: 'tc45', brandId: 'b9', name: 'Tecno Spark 10 Pro (KI7)', lcdScreenCode: 'TEC-KI7-LCD'),
  PhoneModel(id: 'tc46', brandId: 'b9', name: 'Tecno Spark 10C (KI5q)', lcdScreenCode: 'TEC-KI5-LCD'),
  PhoneModel(id: 'tc47', brandId: 'b9', name: 'Tecno Spark 20 (KJ5)', lcdScreenCode: 'TEC-KJ5-LCD'),
  PhoneModel(id: 'tc48', brandId: 'b9', name: 'Tecno Spark 20 Pro (KJ6)', lcdScreenCode: 'TEC-KJ6-LCD'),
  PhoneModel(id: 'tc49', brandId: 'b9', name: 'Tecno Spark 20 Pro Plus (KJ7)', lcdScreenCode: 'TEC-KJ7-AMOLED'),
  PhoneModel(id: 'tc50', brandId: 'b9', name: 'Tecno Spark 20C (BG7)', lcdScreenCode: 'TEC-BG7-LCD'),
  PhoneModel(id: 'tc51', brandId: 'b9', name: 'Tecno Spark 4 (KC8)', lcdScreenCode: 'TEC-KC8-LCD'),
  PhoneModel(id: 'tc52', brandId: 'b9', name: 'Tecno Spark 5 (KD7)', lcdScreenCode: 'TEC-KD7-LCD'),
  PhoneModel(id: 'tc53', brandId: 'b9', name: 'Tecno Spark 5 Air (KD6)', lcdScreenCode: 'TEC-KD6-LCD'),
  PhoneModel(id: 'tc54', brandId: 'b9', name: 'Tecno Spark 6 (KE7)', lcdScreenCode: 'TEC-KE7-LCD'),
  PhoneModel(id: 'tc55', brandId: 'b9', name: 'Tecno Spark 6 Go (KE5)', lcdScreenCode: 'TEC-KE5-LCD'),
  PhoneModel(id: 'tc56', brandId: 'b9', name: 'Tecno Spark 7 (KF6n)', lcdScreenCode: 'TEC-KF6-LCD'),
  PhoneModel(id: 'tc57', brandId: 'b9', name: 'Tecno Spark 8 (KG6)', lcdScreenCode: 'TEC-KG6-LCD'),
  PhoneModel(id: 'tc58', brandId: 'b9', name: 'Tecno Spark 8 Pro (KG8)', lcdScreenCode: 'TEC-KG8-LCD'),
  PhoneModel(id: 'tc59', brandId: 'b9', name: 'Tecno Spark 8C (KG5)', lcdScreenCode: 'TEC-KG5-LCD'),
  PhoneModel(id: 'tc60', brandId: 'b9', name: 'Tecno Spark 9 (KH6)', lcdScreenCode: 'TEC-KH6-LCD'),
  PhoneModel(id: 'tc61', brandId: 'b9', name: 'Tecno Spark 9 Pro (KH7)', lcdScreenCode: 'TEC-KH7-LCD'),
  PhoneModel(id: 'tc62', brandId: 'b9', name: 'Tecno Spark 9T (KH6)', lcdScreenCode: 'TEC-KH6-LCD'),
  PhoneModel(id: 'tc63', brandId: 'b9', name: 'Tecno Spark Go 2020 (KE5)', lcdScreenCode: 'TEC-KE5-LCD'),
  PhoneModel(id: 'tc64', brandId: 'b9', name: 'Tecno Spark Go 2022 (KG5)', lcdScreenCode: 'TEC-KG5-LCD'),
  PhoneModel(id: 'tc65', brandId: 'b9', name: 'Tecno Spark Go 2023 (BF7)', lcdScreenCode: 'TEC-BF7-LCD'),
  PhoneModel(id: 'tc66', brandId: 'b9', name: 'Tecno Spark Go 2024 (BG6)', lcdScreenCode: 'TEC-BG6-LCD'),
  
  // Xiaomi / Redmi Models
  PhoneModel(id: 'xi1', brandId: 'b4', name: 'Redmi 10 (2022)', lcdScreenCode: 'XIA-R10-LCD'),
  PhoneModel(id: 'xi2', brandId: 'b4', name: 'Redmi 10 5G', lcdScreenCode: 'XIA-R10-5G-LCD'),
  PhoneModel(id: 'xi3', brandId: 'b4', name: 'Redmi 10A', lcdScreenCode: 'XIA-R10A-LCD'),
  PhoneModel(id: 'xi4', brandId: 'b4', name: 'Redmi 10C', lcdScreenCode: 'XIA-R10C-LCD'),
  PhoneModel(id: 'xi5', brandId: 'b4', name: 'Redmi 12 4G', lcdScreenCode: 'XIA-R12-LCD'),
  PhoneModel(id: 'xi6', brandId: 'b4', name: 'Redmi 12 5G', lcdScreenCode: 'XIA-R12-LCD'),
  PhoneModel(id: 'xi7', brandId: 'b4', name: 'Redmi 12C', lcdScreenCode: 'XIA-R12C-LCD'),
  PhoneModel(id: 'xi8', brandId: 'b4', name: 'Redmi 13C', lcdScreenCode: 'XIA-R13C-LCD'),
  PhoneModel(id: 'xi9', brandId: 'b4', name: 'Redmi Note 10 4G', lcdScreenCode: 'XIA-N10-AMOLED'),
  PhoneModel(id: 'xi10', brandId: 'b4', name: 'Redmi Note 10 5G', lcdScreenCode: 'XIA-N10-5G-LCD'),
  PhoneModel(id: 'xi11', brandId: 'b4', name: 'Redmi Note 10 Pro', lcdScreenCode: 'XIA-N10P-AMOLED'),
  PhoneModel(id: 'xi12', brandId: 'b4', name: 'Redmi Note 11 4G', lcdScreenCode: 'XIA-N11-AMOLED'),
  PhoneModel(id: 'xi13', brandId: 'b4', name: 'Redmi Note 11s', lcdScreenCode: 'XIA-N11-AMOLED'),
  PhoneModel(id: 'xi14', brandId: 'b4', name: 'Redmi Note 12 4G', lcdScreenCode: 'XIA-N12-AMOLED'),
  PhoneModel(id: 'xi15', brandId: 'b4', name: 'Redmi Note 12 Pro 5G', lcdScreenCode: 'XIA-N12P-OLED'),
  PhoneModel(id: 'xi16', brandId: 'b4', name: 'Redmi Note 12 5G', lcdScreenCode: 'XIA-N12-AMOLED'),
  PhoneModel(id: 'xi17', brandId: 'b4', name: 'Redmi Note 12 Pro 4G', lcdScreenCode: 'XIA-N12P-OLED'),
  PhoneModel(id: 'xi18', brandId: 'b4', name: 'Redmi Note 12s', lcdScreenCode: 'XIA-N12S-AMOLED'),
  PhoneModel(id: 'xi19', brandId: 'b4', name: 'Redmi Note 13 4G', lcdScreenCode: 'XIA-N13-AMOLED'),
  PhoneModel(id: 'xi20', brandId: 'b4', name: 'Redmi Note 13 5G', lcdScreenCode: 'XIA-N13-AMOLED'),
  PhoneModel(id: 'xi21', brandId: 'b4', name: 'Redmi Note 13 Pro 4G', lcdScreenCode: 'XIA-N13P-AMOLED'),
  PhoneModel(id: 'xi22', brandId: 'b4', name: 'Redmi Note 13 Pro 5G', lcdScreenCode: 'XIA-N13P-AMOLED'),
  PhoneModel(id: 'xi23', brandId: 'b4', name: 'Redmi Note 13 Pro Plus 5G', lcdScreenCode: 'XIA-N13PP-OLED'),
  PhoneModel(id: 'xi24', brandId: 'b4', name: 'Redmi Note 8 (2019)', lcdScreenCode: 'XIA-N8-LCD'),
  PhoneModel(id: 'xi25', brandId: 'b4', name: 'Redmi Note 8 Pro', lcdScreenCode: 'XIA-N8P-LCD'),
  PhoneModel(id: 'xi26', brandId: 'b4', name: 'Redmi Note 8T', lcdScreenCode: 'XIA-N8-LCD'),
  PhoneModel(id: 'xi27', brandId: 'b4', name: 'Redmi Note 9', lcdScreenCode: 'XIA-N9-LCD'),
  PhoneModel(id: 'xi28', brandId: 'b4', name: 'Redmi Note 9 Pro', lcdScreenCode: 'XIA-N9P-LCD'),
  PhoneModel(id: 'xi29', brandId: 'b4', name: 'Redmi Note 9s', lcdScreenCode: 'XIA-N9P-LCD'),
  PhoneModel(id: 'xi30', brandId: 'b4', name: 'Redmi Note 9T', lcdScreenCode: 'XIA-N9T-LCD'),
  PhoneModel(id: 'xi31', brandId: 'b4', name: 'Redmi Note 10s', lcdScreenCode: 'XIA-N10-AMOLED'),
  PhoneModel(id: 'xi32', brandId: 'b4', name: 'Redmi Note 11 5G', lcdScreenCode: 'XIA-N11-LCD'),
  PhoneModel(id: 'xi33', brandId: 'b4', name: 'Redmi Note 11 Pro 4G', lcdScreenCode: 'XIA-N11P-AMOLED'),
  PhoneModel(id: 'xi34', brandId: 'b4', name: 'Redmi Note 11 Pro 5G', lcdScreenCode: 'XIA-N11P-AMOLED'),
  PhoneModel(id: 'xi35', brandId: 'b4', name: 'Redmi Note 11 Pro Plus 5G', lcdScreenCode: 'XIA-N11P-AMOLED'),
  PhoneModel(id: 'xi36', brandId: 'b4', name: 'Redmi 9', lcdScreenCode: 'XIA-R9-LCD'),
  PhoneModel(id: 'xi37', brandId: 'b4', name: 'Redmi 9A', lcdScreenCode: 'XIA-R9A-LCD'),
  PhoneModel(id: 'xi38', brandId: 'b4', name: 'Redmi 9C', lcdScreenCode: 'XIA-R9A-LCD'),
  PhoneModel(id: 'xi39', brandId: 'b4', name: 'Redmi 9T', lcdScreenCode: 'XIA-R9T-LCD'),
  PhoneModel(id: 'xi40', brandId: 'b4', name: 'Redmi A1 / A1 Plus', lcdScreenCode: 'XIA-RA1-LCD'),
  PhoneModel(id: 'xi41', brandId: 'b4', name: 'Redmi A2 / A2 Plus', lcdScreenCode: 'XIA-RA1-LCD'),
  PhoneModel(id: 'xi42', brandId: 'b4', name: 'Redmi A3', lcdScreenCode: 'XIA-RA3-LCD'),

  // Vivo Models
  PhoneModel(id: 'vv1', brandId: 'b6', name: 'Vivo V20', lcdScreenCode: 'VIV-V20-AMOLED'),
  PhoneModel(id: 'vv2', brandId: 'b6', name: 'Vivo V20 SE', lcdScreenCode: 'VIV-V20-AMOLED'),
  PhoneModel(id: 'vv3', brandId: 'b6', name: 'Vivo V21 4G/5G', lcdScreenCode: 'VIV-V21-AMOLED'),
  PhoneModel(id: 'vv4', brandId: 'b6', name: 'Vivo V23 5G', lcdScreenCode: 'VIV-V23-AMOLED'),
  PhoneModel(id: 'vv5', brandId: 'b6', name: 'Vivo V23e', lcdScreenCode: 'VIV-V23-AMOLED'),
  PhoneModel(id: 'vv6', brandId: 'b6', name: 'Vivo Y01', lcdScreenCode: 'VIV-Y01-LCD'),
  PhoneModel(id: 'vv7', brandId: 'b6', name: 'Vivo Y02', lcdScreenCode: 'VIV-Y01-LCD'),
  PhoneModel(id: 'vv8', brandId: 'b6', name: 'Vivo Y02s', lcdScreenCode: 'VIV-Y01-LCD'),
  PhoneModel(id: 'vv9', brandId: 'b6', name: 'Vivo Y11 (2019)', lcdScreenCode: 'VIV-Y11-LCD'),
  PhoneModel(id: 'vv10', brandId: 'b6', name: 'Vivo Y12', lcdScreenCode: 'VIV-Y11-LCD'),
  PhoneModel(id: 'vv11', brandId: 'b6', name: 'Vivo Y12s', lcdScreenCode: 'VIV-Y12S-LCD'),
  PhoneModel(id: 'vv12', brandId: 'b6', name: 'Vivo Y15', lcdScreenCode: 'VIV-Y11-LCD'),
  PhoneModel(id: 'vv13', brandId: 'b6', name: 'Vivo Y17', lcdScreenCode: 'VIV-Y11-LCD'),
  PhoneModel(id: 'vv14', brandId: 'b6', name: 'Vivo Y19', lcdScreenCode: 'VIV-Y19-LCD'),
  PhoneModel(id: 'vv15', brandId: 'b6', name: 'Vivo Y20', lcdScreenCode: 'VIV-Y20-LCD'),
  PhoneModel(id: 'vv16', brandId: 'b6', name: 'Vivo Y20s', lcdScreenCode: 'VIV-Y20-LCD'),
  PhoneModel(id: 'vv17', brandId: 'b6', name: 'Vivo Y21', lcdScreenCode: 'VIV-Y21-LCD'),
  PhoneModel(id: 'vv18', brandId: 'b6', name: 'Vivo Y21s', lcdScreenCode: 'VIV-Y21-LCD'),
  PhoneModel(id: 'vv19', brandId: 'b6', name: 'Vivo Y22', lcdScreenCode: 'VIV-Y21-LCD'),
  PhoneModel(id: 'vv20', brandId: 'b6', name: 'Vivo Y22s', lcdScreenCode: 'VIV-Y21-LCD'),
  PhoneModel(id: 'vv21', brandId: 'b6', name: 'Vivo Y30', lcdScreenCode: 'VIV-Y30-LCD'),
  PhoneModel(id: 'vv22', brandId: 'b6', name: 'Vivo Y33s', lcdScreenCode: 'VIV-Y33-LCD'),
  PhoneModel(id: 'vv23', brandId: 'b6', name: 'Vivo Y35', lcdScreenCode: 'VIV-Y35-LCD'),
  PhoneModel(id: 'vv24', brandId: 'b6', name: 'Vivo Y51 (2020)', lcdScreenCode: 'VIV-Y51-LCD'),
  PhoneModel(id: 'vv25', brandId: 'b6', name: 'Vivo Y53s', lcdScreenCode: 'VIV-Y33-LCD'),

  // Itel Models
  PhoneModel(id: 'it1', brandId: 'b10', name: 'Itel A56', lcdScreenCode: 'ITL-A56-LCD'),
  PhoneModel(id: 'it2', brandId: 'b10', name: 'Itel A58', lcdScreenCode: 'ITL-A58-LCD'),
  PhoneModel(id: 'it3', brandId: 'b10', name: 'Itel P36', lcdScreenCode: 'ITL-P36-LCD'),
  PhoneModel(id: 'it4', brandId: 'b10', name: 'Itel P37', lcdScreenCode: 'ITL-P37-LCD'),
  PhoneModel(id: 'it5', brandId: 'b10', name: 'Itel S16', lcdScreenCode: 'ITL-S16-LCD'),
  PhoneModel(id: 'it6', brandId: 'b10', name: 'Itel S17', lcdScreenCode: 'ITL-S17-LCD'),
  PhoneModel(id: 'it7', brandId: 'b10', name: 'Itel Vision 1 Plus', lcdScreenCode: 'ITL-V1P-LCD'),
  PhoneModel(id: 'it8', brandId: 'b10', name: 'Itel Vision 2', lcdScreenCode: 'ITL-V2-LCD'),

  // Legacy/Others (Cleaned up duplicates)
  PhoneModel(id: 'm9', brandId: 'b5', name: 'Oppo A5 (2020)', lcdScreenCode: 'OPP-A5-2020'),
  PhoneModel(id: 'm10', brandId: 'b5', name: 'Oppo A9 (2020)', lcdScreenCode: 'OPP-A5-2020'),
  PhoneModel(id: 'm11', brandId: 'b7', name: 'Realme 5', lcdScreenCode: 'OPP-A5-2020'),
  PhoneModel(id: 'm20', brandId: 'b7', name: 'Realme C11', lcdScreenCode: 'OPP-A5-2020'),
];
